HD44780 Library: Low-level IO functions
Low-level IO functions
Edit these functions (and possibly lcd_write()) to implement your own way of interfacing the LCD.
Functions
void LCD_DATA_OUT (uint8_t data)
Set data outputs.
void LCD_EN (uint8_t en)
Set the EN output pin.
void LCD_OUT_UPDATE (void)
Update output port from buffer.
void LCD_RS (uint8_t rs)
Set the RS output pin.
Detailed Description
Edit these functions (and possibly lcd_write()) to implement your own way of interfacing the LCD.
Function Documentation
void LCD_DATA_OUT (uint8_t data) [inline]
Set data outputs.
In 4bit mode, this sets D4-D7 to bits 0-3 of the input value. In 8bit mode (not yet implemented!), this sets D0-D7 to the input value.
Definition at line 34 of file lcd.c.
References LCD_OUT_UPDATE().
Referenced by lcd_nibble().
void LCD_EN (uint8_t en) [inline]
Set the EN output pin.
"EN" (Enable) is the clock pin of the HD44780
Definition at line 56 of file lcd.c.
References lcd_controller, and LCD_OUT_UPDATE().
Referenced by lcd_init(), and lcd_nibble().
void LCD_OUT_UPDATE (void)
Update output port from buffer.
This does nothing for direct output. For shift registers it sends the (modified) output buffer to the shift register. You can control inlining of this function by defining LCD_OUT_UPDATE_NEVER_INLINE (less size but less performance) or LCD_OUT_UPDATE_ALWAYS_INLINE (more size and more performance). By default it is inlined for all cases except LCD_MODE_SHIFT_4BIT and LCD_MODE_SHIFT_8BIT.
Definition at line 92 of file lcd.c.
Referenced by LCD_DATA_OUT(), LCD_EN(), and LCD_RS().
void LCD_RS (uint8_t rs) [inline]
Set the RS output pin.
RS
Definition at line 43 of file lcd.c.
References LCD_OUT_UPDATE().
Referenced by lcd_init(), and lcd_write().